import { Protest_Guerrilla } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Protest_Guerrilla({weight:"400" ,subsets: ["latin"] });

export const metadata = {
  title: "Ehsan - Junior Frontend Developer",
  description: "Generated by Ehsan Hosseini",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/3.png" />
      </head>
      <body className={`overflow-y-scroll selection:bg-slate-50 selection:text-black flex flex-col justify-between h-dvh`}>
        <Navbar className={`${inter.className} text-lg`}></Navbar>
        {children}

        <Footer/>
        </body>

    </html>
  );
}


